### ISSUE TITLE
Add support for PyCharm 2020.1

### ISSUE THREAD

**Issue by autoferrit** [meanmail/PyAnnotations#2]
**Describe the bug**
This plugin is not supported in PyCharm 2020.1

**To Reproduce**
Upgrade from 2019.x to 2020.1

**Expected behavior**
Should be compatible and not get compatability message

**Screenshots**
![image](https://user-images.githubusercontent.com/89895/79360585-fe338580-7ef8-11ea-91fa-1af54dff349d.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Linux ferritprime 5.4.28-1-MANJARO #1 SMP PREEMPT Wed Mar 25 12:45:29 UTC 2020 x86_64 GNU/Linux

 - Product: PyCharm 2020.1
 - Version: Build #PY-201.6668.115, built on April 7, 2020
 - Project SDK: [Python 3.7.1]

**Comment by meanmail** [comment]
The plugin has been updated. The new version will be available for download in two business days.

**Comment by meanmail** [comment]
Plugin Python Annotations 2020.1 is Released! https://meanmail.dev/plugin/3
